apiVersion: v1
kind: Service
metadata: 
  name: ecommerce
spec:
  selector:
    app: ecommerce
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 5
  selector: 
    matchLabels: 
      app: kubeusers
  template:
    metadata: 
      labels: 
        app: kubeusers
    spec:
      containers: 
      - name: kubecontainer
        image:  lombris/usercreator
        ports: 
          - containerPort: 8080
        env: 
          - name: MONGO_URL
            value: mongodb+srv://FDR98:Hesoyam123@cluster0.gkja86y.mongodb.net/?retryWrites=true&w=majority
        imagePullPolicy: Always
